name: aliyunoss_plus_flutter
description: Upload
version: 1.0.1
homepage: https://github.com/tobesteve/aliyunoss_plus_flutter
repository: https://github.com/tobesteve/aliyunoss_plus_flutter
environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio : ^5.3.2
  crypto: ^3.0.2
  intl: ^0.18.0
  xml: ^6.1.0
  shared_preferences: ^2.0.15
  mime: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
